// <auto-generated />
using System;
using JTCM.DAL.DBModel;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace JTCM.DAL.Migrations
{
    [DbContext(typeof(JtcmContext))]
    partial class JtcmContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-preview3-35497")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("JTCM.DAL.DBModel.WorkflowRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150);

                    b.HasKey("Id");

                    b.ToTable("WorkflowRole");
                });

            modelBuilder.Entity("JTCM.DAL.DBModel.WorkflowRoleUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("WorkflowRoleId");

                    b.Property<int?>("WorkflowUserId");

                    b.HasKey("Id");

                    b.HasIndex("WorkflowRoleId");

                    b.HasIndex("WorkflowUserId");

                    b.ToTable("WorkflowRoleUser");
                });

            modelBuilder.Entity("JTCM.DAL.DBModel.WorkflowUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FirstName")
                        .HasMaxLength(150);

                    b.Property<string>("LastName")
                        .HasMaxLength(150);

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.ToTable("WorkflowUser");
                });

            modelBuilder.Entity("JTCM.DAL.DBModel.WorkflowRoleUser", b =>
                {
                    b.HasOne("JTCM.DAL.DBModel.WorkflowRole", "WorkflowRole")
                        .WithMany()
                        .HasForeignKey("WorkflowRoleId");

                    b.HasOne("JTCM.DAL.DBModel.WorkflowUser", "WorkflowUser")
                        .WithMany()
                        .HasForeignKey("WorkflowUserId");
                });
#pragma warning restore 612, 618
        }
    }
}
